import React,{useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Mic,CheckSquare,StickyNote,Camera,UserRound,CalendarDays}from'lucide-react';
import'./styles.css';

type Draft={kind:'todo'|'pinboard'|null,title:string,due?:string,assignee?:string};
const weekdays=['sonntag','montag','dienstag','mittwoch','donnerstag','freitag','samstag'];
function nextWeekday(name:string){const target=weekdays.indexOf(name.toLowerCase());if(target<0)return;const d=new Date();const delta=(target-d.getDay()+7)%7||7;d.setDate(d.getDate()+delta);return d.toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});}
function parseSpeech(raw:string):Draft{let s=raw.trim();let kind:null|'todo'|'pinboard'=null;if(/pinnwand|pinnwandnotiz/i.test(s))kind='pinboard';else if(/aufgabe|todo|erinnerung/i.test(s))kind='todo';let due;for(const w of weekdays){if(new RegExp('(?:fällig\\s+)?(?:am\\s+|nächsten?\\s+)?'+w,'i').test(s)){due=nextWeekday(w);break}}let assignee;const m=s.match(/(?:für\s+)([A-ZÄÖÜ][A-Za-zÄÖÜäöüß-]+)/)||s.match(/^([A-ZÄÖÜ][A-Za-zÄÖÜäöüß-]+)\s+soll/);if(m)assignee=m[1];s=s.replace(/^(schnelle\s+)?(aufgabe|todo|erinnerung|notiz|pinnwandnotiz)\s*:?\s*/i,'').replace(/,?\s*fällig.*$/i,'').trim();return{kind,title:s,due,assignee};}
function App(){const[status,setStatus]=useState('Bereit');const[draft,setDraft]=useState<Draft|null>(null);const[fileCount,setFileCount]=useState(0);const camera=useRef<HTMLInputElement>(null);
const listen=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setStatus('Spracherkennung wird von diesem Browser nicht unterstützt.');return}const r=new SR();r.lang='de-DE';r.interimResults=false;r.onstart=()=>setStatus('Ich höre zu …');r.onerror=()=>setStatus('Spracheingabe fehlgeschlagen.');r.onresult=(e:any)=>{const spoken=e.results[0][0].transcript;const p=parseSpeech(spoken);setDraft(p);setStatus(p.kind===null&&/^notiz\b/i.test(spoken)?'Notiz erkannt – Todo oder Pinnwand?':'Eingabe erkannt. Bitte prüfen.');};r.start()};
return <main><header><div><small>ADLER NEU</small><h1>Mobile</h1></div><UserRound/></header><section className="hero"><button className="mic" onClick={listen}><Mic size={42}/></button><h2>Spracheingabe</h2><p>{status}</p></section><section className="actions"><button onClick={listen}><CheckSquare/>Aufgabe / Erinnerung / Todo</button><button onClick={listen}><StickyNote/>Pinnwand-Notiz</button></section>{draft&&<section className="card"><h3>Erkannter Eintrag</h3>{draft.kind===null&&<div className="choice"><button onClick={()=>setDraft({...draft,kind:'todo'})}>Todo</button><button onClick={()=>setDraft({...draft,kind:'pinboard'})}>Pinnwand</button></div>}<label>Titel<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>{draft.assignee&&<p><UserRound/> {draft.assignee}</p>}{draft.due&&<p><CalendarDays/> {draft.due}</p>}<button className="photo" onClick={()=>camera.current?.click()}><Camera/> Bild hinzufügen {fileCount>0?'('+fileCount+')':''}</button><input ref={camera} hidden type="file" accept="image/*" capture="environment" multiple onChange={e=>setFileCount(e.target.files?.length||0)}/><button className="save" disabled={!draft.kind||!draft.title}>Eintrag vorbereiten</button></section>}<footer>Adler Neu · PWA Prototyp</footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);