import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{Mic,CheckSquare,StickyNote,Camera,UserRound,CalendarDays}from'lucide-react';import'./styles.css';import{parseVoice}from'./voiceParser';import{adlerApi}from'./api';import{resolveAssignee}from'./assigneeResolver';import type{VoiceDraft,EntryKind,Employee,EntryPayload}from'./types';
function formatDate(v?:string){if(!v)return'';return new Date(v+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}
function dueAt(d:VoiceDraft){return d.dueDate?d.dueDate+'T'+(d.dueTime||'17:00')+':00':undefined}
function App(){const[status,setStatus]=useState('Bereit');const[draft,setDraft]=useState<VoiceDraft|null>(null);const[files,setFiles]=useState<File[]>([]);const[employees,setEmployees]=useState<Employee[]>([]);const[selectedEmployeeId,setSelectedEmployeeId]=useState('');const[saving,setSaving]=useState(false);const camera=useRef<HTMLInputElement>(null);
useEffect(()=>{adlerApi.employees().then(setEmployees).catch(()=>setStatus('Entwurfsmodus – Adler API noch nicht erreichbar.'))},[]);
useEffect(()=>{if(!draft?.assigneeName||!employees.length){setSelectedEmployeeId('');return}const r=resolveAssignee(draft.assigneeName,employees);if(r.status==='matched')setSelectedEmployeeId(r.employee!.id);else{setSelectedEmployeeId('');if(r.status==='ambiguous')setStatus('Mitarbeitername ist mehrdeutig – bitte auswählen.');if(r.status==='missing')setStatus('Mitarbeiter wurde nicht gefunden – bitte auswählen.')}},[draft?.assigneeName,employees]);
const listen=(forced?:EntryKind)=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setStatus('Spracherkennung wird von diesem Browser nicht unterstützt.');return}const r=new SR();r.lang='de-DE';r.interimResults=false;r.onstart=()=>setStatus('Ich höre zu …');r.onerror=()=>setStatus('Spracheingabe fehlgeschlagen.');r.onresult=(e:any)=>{const spoken=e.results[0][0].transcript;const p=parseVoice(spoken);if(forced){p.kind=forced;p.needsDestinationChoice=false}setDraft(p);setStatus(p.needsDestinationChoice?'Notiz erkannt – Todo oder Pinnwand?':'Eingabe erkannt. Bitte prüfen.');};r.start()};
const choose=(kind:EntryKind)=>draft&&setDraft({...draft,kind,needsDestinationChoice:false});
const save=async()=>{if(!draft?.kind||!draft.title)return;setSaving(true);setStatus('Wird gespeichert …');try{const attachment_ids:string[]=[];for(const file of files){const uploaded=await adlerApi.uploadAttachment(file);attachment_ids.push(uploaded.id)}const payload:EntryPayload={title:draft.title,description:draft.description||undefined,due_at:dueAt(draft),assigned_user_ids:selectedEmployeeId?[selectedEmployeeId]:[],attachment_ids};await adlerApi.createEntry(draft.kind,payload);setStatus(draft.kind==='todo'?'Aufgabe gespeichert.':'Pinnwand-Notiz gespeichert.');setDraft(null);setFiles([]);setSelectedEmployeeId('')}catch(e){setStatus(e instanceof Error?e.message:'Speichern fehlgeschlagen.')}finally{setSaving(false)}};
return <main><header><div><small>ADLER NEU</small><h1>Mobile</h1></div><UserRound/></header><section className="hero"><button className="mic" onClick={()=>listen()} aria-label="Spracheingabe starten"><Mic size={42}/></button><h2>Spracheingabe</h2><p>{status}</p></section><section className="actions"><button onClick={()=>listen('todo')}><CheckSquare/>Aufgabe / Erinnerung / Todo</button><button onClick={()=>listen('pinboard')}><StickyNote/>Pinnwand-Notiz</button></section>{draft&&<section className="card"><h3>Eintrag prüfen</h3>{draft.needsDestinationChoice&&<div className="choice"><button onClick={()=>choose('todo')}>Todo</button><button onClick={()=>choose('pinboard')}>Pinnwand</button></div>}<label>Titel<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Beschreibung<textarea value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>{draft.dueDate&&<p><CalendarDays/> Fällig: {formatDate(draft.dueDate)} {draft.dueTime&&'um '+draft.dueTime+' Uhr'}</p>}<label><span><UserRound size={17}/> Mitarbeiter</span><select value={selectedEmployeeId} onChange={e=>setSelectedEmployeeId(e.target.value)}><option value="">Nicht zugewiesen</option>{employees.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label>{draft.assigneeName&&!selectedEmployeeId&&employees.length>0&&<p className="warning">Gesprochen: {draft.assigneeName} – bitte Mitarbeiter bestätigen.</p>}<button className="photo" onClick={()=>camera.current?.click()}><Camera/> Bilder hinzufügen {files.length>0?'('+files.length+')':''}</button><input ref={camera} hidden type="file" accept="image/*" capture="environment" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/>{files.length>0&&<div className="previews">{files.map((f,i)=><div key={f.name+i}>{f.name}<button onClick={()=>setFiles(files.filter((_,x)=>x!==i))}>×</button></div>)}</div>}<button className="save" disabled={saving||!draft.kind||!draft.title} onClick={save}>{saving?'Speichert …':'Bestätigen & speichern'}</button></section>}<footer>Adler Neu · Mobile</footer></main>}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));createRoot(document.getElementById('root')!).render(<App/>);